### PR TITLE
Fixes #184 - Build error fixed

### LINKED ISSUE #184: Build failure on 32-bit Win
It appears we have a lint warning triggering a build failure for 32-bit Windows only.

https://ci.appveyor.com/project/MaidSafe-QA/safe-core/build/1.0.23/job/y6meba3dge0x4taa

This has been slipping through the net because we allow 32-bit builds to fail the AppVeyor tests due to the ongoing crypto issue.

### PR DESCRIPTION
**Pull request by krishnaIndia**

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

File: src/id/public_id_type.rs [hunk 1]
```diff
@@ -165,7 +165,7 @@ mod test {
         }
 
         let signature = ::sodiumoxide::crypto::sign::Signature(signature_arr);
-
-        assert_eq!(&signature.0, &public_maid.signature().0);
+        assert_eq!(&signature.0.iter().map(|x| x).collect::<Vec<_>>(),
```
Comment (ustulation) [inline src/id/public_id_type.rs]: use `slice_equal` - it's there in `utility.rs`
